"""donation and ledger

Revision ID: 3c8c34fc3b38
Revises: a8f136b3eea3
Create Date: 2025-05-04 01:44:41.207928

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c8c34fc3b38'
down_revision = 'a8f136b3eea3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('donation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('message', sa.String(length=255), nullable=True),
    sa.Column('fundraiser_id', sa.String(length=36), nullable=False),
    sa.Column('donor_name', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['fundraiser_id'], ['fundraiser.fundraiser_id'], name=op.f('fk_donation_fundraiser_id_fundraiser')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_donation'))
    )
    op.create_table('transaction_ledger',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transaction_ref', sa.String(length=36), nullable=False),
    sa.Column('transaction_type', sa.Enum('DONATION', 'WITHDRAWAL', name='transactiontype'), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('fundraiser_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['fundraiser_id'], ['fundraiser.fundraiser_id'], name=op.f('fk_transaction_ledger_fundraiser_id_fundraiser')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_transaction_ledger_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_transaction_ledger')),
    sa.UniqueConstraint('transaction_ref', name=op.f('uq_transaction_ledger_transaction_ref'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transaction_ledger')
    op.drop_table('donation')
    # ### end Alembic commands ###
