"""add current status to dontation 

Revision ID: 3d5fbcd5a8f8
Revises: f5855ab1769e
Create Date: 2025-05-04 22:30:47.422660

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d5fbcd5a8f8'
down_revision = 'f5855ab1769e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_status', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donation', schema=None) as batch_op:
        batch_op.drop_column('current_status')

    # ### end Alembic commands ###
