"""update fundraiser table uuid

Revision ID: a8f136b3eea3
Revises: c2d3850787d5
Create Date: 2025-05-04 01:02:16.023399

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8f136b3eea3'
down_revision = 'c2d3850787d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fundraiser', schema=None) as batch_op:
        batch_op.alter_column('fundraiser_id',
               existing_type=sa.VARCHAR(length=36),
               type_=sa.String(length=8),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fundraiser', schema=None) as batch_op:
        batch_op.alter_column('fundraiser_id',
               existing_type=sa.String(length=8),
               type_=sa.VARCHAR(length=36),
               existing_nullable=True)

    # ### end Alembic commands ###
