"""added request id to donation

Revision ID: d650c351a212
Revises: 3d5fbcd5a8f8
Create Date: 2025-05-04 22:56:17.584474

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd650c351a212'
down_revision = '3d5fbcd5a8f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('merchant_request_id', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donation', schema=None) as batch_op:
        batch_op.drop_column('merchant_request_id')

    # ### end Alembic commands ###
