"""added transaction_ref to the donation

Revision ID: d67c64744a6a
Revises: d650c351a212
Create Date: 2025-05-05 00:52:00.338642

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd67c64744a6a'
down_revision = 'd650c351a212'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('transaction_ref', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('donation', schema=None) as batch_op:
        batch_op.drop_column('transaction_ref')

    # ### end Alembic commands ###
